# https://dev.azure.com/dylan-hasler

trigger:
  branches:
    include:
    - master
pr: none

variables:
  - name: versionBuilder
    value: '2.0'
  - group: docker


jobs:
- template: ThePicklenat0r/hassio-addons/blob/master/.azure/azp-template-addon.yml
  parameters:
    addon: 'ngrok'
    arch: '--all'