# https://dev.azure.com/dylan-hasler

resources:
  repositories:
    - repository: azp-templates
      type: github
      name: ThePicklenat0r/azp-templates
      endpoint: ThePicklenat0r

trigger:
  tags:
    include:
      - '*'
pr: none

variables:
  - name: versionBuilder
    value: '6.6'
  - group: docker


jobs:
- template: /hassio-addons/azp-template-addon.yml@azp-templates
  parameters:
    addon: 'ngrok'
    arch: '--all'