# https://dev.azure.com/dylan-hasler

resources:
  repositories:
    - repository: templates
      type: github
      name: ThePicklenat0r/azp-templates
      endpoint: ThePicklenat0r

trigger:
  branches:
    include:
      - master
pr: none

variables:
  - name: versionBuilder
    value: '6.6'
  - group: docker


jobs:
- template: /hassio-addons/jobs/azp-build-addon.yml@templates
  parameters:
    addon: 'ngrok'
    arch: '--all'