# https://dev.azure.com/dylan-hasler

trigger:
  branches:
    include:
    - master
pr: none

variables:
  - name: versionBuilder
    value: '2.0'
  - group: docker
  - name: addon
    value: 'ngrok'
  - name: arch
    value: '--all'

jobs:

- job: '$(addon)'
  condition: eq(variables['Build.SourceBranchName'], 'master')
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 360
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerToken)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --addon $(arch) -t /data/$(addon) \
        --docker-hub homeassistant --docker-hub-check
    displayName: 'Build $(addon)'